-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "score" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "commentKarma" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "postKarma" INTEGER NOT NULL DEFAULT 0;
